// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/kriku/kpukbot/internal/clients/telegram"
	"github.com/kriku/kpukbot/internal/config"
	"github.com/kriku/kpukbot/internal/handlers"
	"github.com/kriku/kpukbot/internal/logger"
	"github.com/kriku/kpukbot/internal/repository/messages"
	messages2 "github.com/kriku/kpukbot/internal/services/messages"
)

// Injectors from wire.go:

func InitAppLocal() (App, error) {
	slogLogger := logger.NewLogger()
	configConfig := config.NewConfig()
	handlerFunc := handlers.NewDefaultHandler(slogLogger)
	messengerClient, err := telegram.NewTelegramClient(configConfig, handlerFunc)
	if err != nil {
		return App{}, err
	}
	messagesRepository, err := messages.NewFirestoreRepository(configConfig)
	if err != nil {
		return App{}, err
	}
	telegramMessagesService := messages2.NewTelegramMessagesService(messagesRepository, slogLogger)
	app := NewApp(slogLogger, messengerClient, messagesRepository, telegramMessagesService)
	return app, nil
}

// wire.go:

var baseSet = wire.NewSet(config.NewConfig, logger.NewLogger, handlers.NewDefaultHandler, telegram.NewTelegramClient, messages2.NewTelegramMessagesService, messages.NewFirestoreRepository, NewApp)
