// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/google/wire"
	"github.com/kriku/kpukbot/internal/config"
	"github.com/kriku/kpukbot/internal/handlers"
	"github.com/kriku/kpukbot/internal/repository"
	"github.com/kriku/kpukbot/internal/services"
)

// Injectors from wire.go:

func InitAppLocal() (App, error) {
	configConfig := config.NewConfig()
	aiServiceInterface, err := services.NewGeminiService(configConfig)
	if err != nil {
		return App{}, err
	}
	repositoryRepository, err := repository.NewFirestoreRepository(configConfig)
	if err != nil {
		return App{}, err
	}
	telegramService, err := services.NewTelegramService(configConfig, aiServiceInterface, repositoryRepository)
	if err != nil {
		return App{}, err
	}
	webhookHandler := handlers.NewWebhookHandler(telegramService)
	app := NewApp(telegramService, aiServiceInterface, webhookHandler, repositoryRepository)
	return app, nil
}

// wire.go:

var baseSet = wire.NewSet(config.NewConfig, handlers.NewWebhookHandler, services.NewGeminiService, services.NewTelegramService, repository.NewFirestoreRepository, wire.Bind(new(handlers.TelegramUpdateHandler), new(*services.TelegramService)), NewApp)
